
name: Builds and Tests

on:
  push:
    branches-ignore:
      - "main"

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: 'stable'

      - name: Flutter Configure
        run: |
          flutter pub get
          flutter config --enable-${{ matrix.os }}-desktop

      - name: Astali build
        run: flutter build ${{ matrix.os }}

      - name: Unit tests run
        run: |
          flutter pub run build_runner build
          flutter test ./test/unit/**/*.tests.dart
