
name: Builds and Tests

on:
  push:
    branches-ignore:
      - "main"

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Flutter Configure
        run: |
          flutter pub get
          flutter config --enable-windows-desktop

      - name: Astali build
        run: flutter build windows

      - name: Unit tests run
        run: |
          flutter pub run build_runner build
          flutter test ./test/unit/**/*.tests.dart
